/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CompanyWhereUniqueInput } from "../../company/base/CompanyWhereUniqueInput";
import { ValidateNested, IsOptional, IsBoolean } from "class-validator";
import { Type } from "class-transformer";
import { CustomerWhereUniqueInput } from "../../customer/base/CustomerWhereUniqueInput";
import { ReservableSlotWhereUniqueInput } from "../../reservableSlot/base/ReservableSlotWhereUniqueInput";
import { ReservationNotificationCreateNestedManyWithoutReservationsInput } from "./ReservationNotificationCreateNestedManyWithoutReservationsInput";
@InputType()
class ReservationCreateInput {
  @ApiProperty({
    required: false,
    type: () => CompanyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CompanyWhereUniqueInput)
  @IsOptional()
  @Field(() => CompanyWhereUniqueInput, {
    nullable: true,
  })
  company?: CompanyWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: () => CustomerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CustomerWhereUniqueInput)
  @Field(() => CustomerWhereUniqueInput)
  customer!: CustomerWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isAccepted?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => ReservableSlotWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ReservableSlotWhereUniqueInput)
  @IsOptional()
  @Field(() => ReservableSlotWhereUniqueInput, {
    nullable: true,
  })
  reservableSlot?: ReservableSlotWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ReservationNotificationCreateNestedManyWithoutReservationsInput,
  })
  @ValidateNested()
  @Type(() => ReservationNotificationCreateNestedManyWithoutReservationsInput)
  @IsOptional()
  @Field(
    () => ReservationNotificationCreateNestedManyWithoutReservationsInput,
    {
      nullable: true,
    }
  )
  reservationNotifications?: ReservationNotificationCreateNestedManyWithoutReservationsInput;
}
export { ReservationCreateInput };
