/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateTimeSlotArgs } from "./CreateTimeSlotArgs";
import { UpdateTimeSlotArgs } from "./UpdateTimeSlotArgs";
import { DeleteTimeSlotArgs } from "./DeleteTimeSlotArgs";
import { TimeSlotFindManyArgs } from "./TimeSlotFindManyArgs";
import { TimeSlotFindUniqueArgs } from "./TimeSlotFindUniqueArgs";
import { TimeSlot } from "./TimeSlot";
import { ReservableSlotFindManyArgs } from "../../reservableSlot/base/ReservableSlotFindManyArgs";
import { ReservableSlot } from "../../reservableSlot/base/ReservableSlot";
import { Company } from "../../company/base/Company";
import { TimeSlotService } from "../timeSlot.service";

@graphql.Resolver(() => TimeSlot)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class TimeSlotResolverBase {
  constructor(
    protected readonly service: TimeSlotService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "TimeSlot",
    action: "read",
    possession: "any",
  })
  async _timeSlotsMeta(
    @graphql.Args() args: TimeSlotFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [TimeSlot])
  @nestAccessControl.UseRoles({
    resource: "TimeSlot",
    action: "read",
    possession: "any",
  })
  async timeSlots(
    @graphql.Args() args: TimeSlotFindManyArgs
  ): Promise<TimeSlot[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => TimeSlot, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "TimeSlot",
    action: "read",
    possession: "own",
  })
  async timeSlot(
    @graphql.Args() args: TimeSlotFindUniqueArgs
  ): Promise<TimeSlot | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => TimeSlot)
  @nestAccessControl.UseRoles({
    resource: "TimeSlot",
    action: "create",
    possession: "any",
  })
  async createTimeSlot(
    @graphql.Args() args: CreateTimeSlotArgs
  ): Promise<TimeSlot> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        company: {
          connect: args.data.company,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => TimeSlot)
  @nestAccessControl.UseRoles({
    resource: "TimeSlot",
    action: "update",
    possession: "any",
  })
  async updateTimeSlot(
    @graphql.Args() args: UpdateTimeSlotArgs
  ): Promise<TimeSlot | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          company: {
            connect: args.data.company,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => TimeSlot)
  @nestAccessControl.UseRoles({
    resource: "TimeSlot",
    action: "delete",
    possession: "any",
  })
  async deleteTimeSlot(
    @graphql.Args() args: DeleteTimeSlotArgs
  ): Promise<TimeSlot | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [ReservableSlot])
  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "read",
    possession: "any",
  })
  async reservableSlots(
    @graphql.Parent() parent: TimeSlot,
    @graphql.Args() args: ReservableSlotFindManyArgs
  ): Promise<ReservableSlot[]> {
    const results = await this.service.findReservableSlots(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Company, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Company",
    action: "read",
    possession: "any",
  })
  async company(@graphql.Parent() parent: TimeSlot): Promise<Company | null> {
    const result = await this.service.getCompany(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
