/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateCompanyTypeArgs } from "./CreateCompanyTypeArgs";
import { UpdateCompanyTypeArgs } from "./UpdateCompanyTypeArgs";
import { DeleteCompanyTypeArgs } from "./DeleteCompanyTypeArgs";
import { CompanyTypeFindManyArgs } from "./CompanyTypeFindManyArgs";
import { CompanyTypeFindUniqueArgs } from "./CompanyTypeFindUniqueArgs";
import { CompanyType } from "./CompanyType";
import { CompanyFindManyArgs } from "../../company/base/CompanyFindManyArgs";
import { Company } from "../../company/base/Company";
import { CompanyTypeService } from "../companyType.service";

@graphql.Resolver(() => CompanyType)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CompanyTypeResolverBase {
  constructor(
    protected readonly service: CompanyTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CompanyType",
    action: "read",
    possession: "any",
  })
  async _companyTypesMeta(
    @graphql.Args() args: CompanyTypeFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [CompanyType])
  @nestAccessControl.UseRoles({
    resource: "CompanyType",
    action: "read",
    possession: "any",
  })
  async companyTypes(
    @graphql.Args() args: CompanyTypeFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CompanyType[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "CompanyType",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => CompanyType, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CompanyType",
    action: "read",
    possession: "own",
  })
  async companyType(
    @graphql.Args() args: CompanyTypeFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CompanyType | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "CompanyType",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => CompanyType)
  @nestAccessControl.UseRoles({
    resource: "CompanyType",
    action: "create",
    possession: "any",
  })
  async createCompanyType(
    @graphql.Args() args: CreateCompanyTypeArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CompanyType> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "CompanyType",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"CompanyType"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => CompanyType)
  @nestAccessControl.UseRoles({
    resource: "CompanyType",
    action: "update",
    possession: "any",
  })
  async updateCompanyType(
    @graphql.Args() args: UpdateCompanyTypeArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CompanyType | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "CompanyType",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"CompanyType"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CompanyType)
  @nestAccessControl.UseRoles({
    resource: "CompanyType",
    action: "delete",
    possession: "any",
  })
  async deleteCompanyType(
    @graphql.Args() args: DeleteCompanyTypeArgs
  ): Promise<CompanyType | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Company])
  @nestAccessControl.UseRoles({
    resource: "CompanyType",
    action: "read",
    possession: "any",
  })
  async companies(
    @graphql.Parent() parent: CompanyType,
    @graphql.Args() args: CompanyFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Company[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Company",
    });
    const results = await this.service.findCompanies(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
