/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";

import {
  Prisma,
  Company,
  CompanySetNotification,
  FavoriteCompany,
  LastSeenCompany,
  TimeSlot,
  Address,
  CompanyType,
  Customer,
} from "@prisma/client";

export class CompanyServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.CompanyFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CompanyFindManyArgs>
  ): Promise<number> {
    return this.prisma.company.count(args);
  }

  async findMany<T extends Prisma.CompanyFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CompanyFindManyArgs>
  ): Promise<Company[]> {
    return this.prisma.company.findMany(args);
  }
  async findOne<T extends Prisma.CompanyFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CompanyFindUniqueArgs>
  ): Promise<Company | null> {
    return this.prisma.company.findUnique(args);
  }
  async create<T extends Prisma.CompanyCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CompanyCreateArgs>
  ): Promise<Company> {
    return this.prisma.company.create<T>(args);
  }
  async update<T extends Prisma.CompanyUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CompanyUpdateArgs>
  ): Promise<Company> {
    return this.prisma.company.update<T>(args);
  }
  async delete<T extends Prisma.CompanyDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CompanyDeleteArgs>
  ): Promise<Company> {
    return this.prisma.company.delete(args);
  }

  async findCompanySetNotifications(
    parentId: string,
    args: Prisma.CompanySetNotificationFindManyArgs
  ): Promise<CompanySetNotification[]> {
    return this.prisma.company
      .findUnique({
        where: { id: parentId },
      })
      .companySetNotifications(args);
  }

  async findFavoriteCompanies(
    parentId: string,
    args: Prisma.FavoriteCompanyFindManyArgs
  ): Promise<FavoriteCompany[]> {
    return this.prisma.company
      .findUnique({
        where: { id: parentId },
      })
      .favoriteCompanies(args);
  }

  async findLastSeenCompanies(
    parentId: string,
    args: Prisma.LastSeenCompanyFindManyArgs
  ): Promise<LastSeenCompany[]> {
    return this.prisma.company
      .findUnique({
        where: { id: parentId },
      })
      .lastSeenCompanies(args);
  }

  async findTimeSlots(
    parentId: string,
    args: Prisma.TimeSlotFindManyArgs
  ): Promise<TimeSlot[]> {
    return this.prisma.company
      .findUnique({
        where: { id: parentId },
      })
      .timeSlots(args);
  }

  async getAddress(parentId: string): Promise<Address | null> {
    return this.prisma.company
      .findUnique({
        where: { id: parentId },
      })
      .address();
  }

  async getCompanyType(parentId: string): Promise<CompanyType | null> {
    return this.prisma.company
      .findUnique({
        where: { id: parentId },
      })
      .companyType();
  }

  async getOwner(parentId: string): Promise<Customer | null> {
    return this.prisma.company
      .findUnique({
        where: { id: parentId },
      })
      .owner();
  }
}
