/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ReservationNotificationService } from "../reservationNotification.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReservationNotificationCreateInput } from "./ReservationNotificationCreateInput";
import { ReservationNotificationWhereInput } from "./ReservationNotificationWhereInput";
import { ReservationNotificationWhereUniqueInput } from "./ReservationNotificationWhereUniqueInput";
import { ReservationNotificationFindManyArgs } from "./ReservationNotificationFindManyArgs";
import { ReservationNotificationUpdateInput } from "./ReservationNotificationUpdateInput";
import { ReservationNotification } from "./ReservationNotification";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReservationNotificationControllerBase {
  constructor(
    protected readonly service: ReservationNotificationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ReservationNotification",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ReservationNotification })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: ReservationNotificationCreateInput
  ): Promise<ReservationNotification> {
    return await this.service.create({
      data: {
        ...data,

        notification: {
          connect: data.notification,
        },

        reservation: {
          connect: data.reservation,
        },
      },
      select: {
        createdAt: true,
        customText: true,
        id: true,

        notification: {
          select: {
            id: true,
          },
        },

        reservation: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ReservationNotification",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [ReservationNotification] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ReservationNotificationFindManyArgs)
  async findMany(
    @common.Req() request: Request
  ): Promise<ReservationNotification[]> {
    const args = plainToClass(
      ReservationNotificationFindManyArgs,
      request.query
    );
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        customText: true,
        id: true,

        notification: {
          select: {
            id: true,
          },
        },

        reservation: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ReservationNotification",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ReservationNotification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ReservationNotificationWhereUniqueInput
  ): Promise<ReservationNotification | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        customText: true,
        id: true,

        notification: {
          select: {
            id: true,
          },
        },

        reservation: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ReservationNotification",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ReservationNotification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ReservationNotificationWhereUniqueInput,
    @common.Body() data: ReservationNotificationUpdateInput
  ): Promise<ReservationNotification | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          notification: {
            connect: data.notification,
          },

          reservation: {
            connect: data.reservation,
          },
        },
        select: {
          createdAt: true,
          customText: true,
          id: true,

          notification: {
            select: {
              id: true,
            },
          },

          reservation: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "ReservationNotification",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ReservationNotification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ReservationNotificationWhereUniqueInput
  ): Promise<ReservationNotification | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          customText: true,
          id: true,

          notification: {
            select: {
              id: true,
            },
          },

          reservation: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
