/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { NotificationService } from "../notification.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { NotificationCreateInput } from "./NotificationCreateInput";
import { NotificationWhereInput } from "./NotificationWhereInput";
import { NotificationWhereUniqueInput } from "./NotificationWhereUniqueInput";
import { NotificationFindManyArgs } from "./NotificationFindManyArgs";
import { NotificationUpdateInput } from "./NotificationUpdateInput";
import { Notification } from "./Notification";
import { CompanySetNotificationFindManyArgs } from "../../companySetNotification/base/CompanySetNotificationFindManyArgs";
import { CompanySetNotification } from "../../companySetNotification/base/CompanySetNotification";
import { CompanySetNotificationWhereUniqueInput } from "../../companySetNotification/base/CompanySetNotificationWhereUniqueInput";
import { ReservationNotificationFindManyArgs } from "../../reservationNotification/base/ReservationNotificationFindManyArgs";
import { ReservationNotification } from "../../reservationNotification/base/ReservationNotification";
import { ReservationNotificationWhereUniqueInput } from "../../reservationNotification/base/ReservationNotificationWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class NotificationControllerBase {
  constructor(
    protected readonly service: NotificationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Notification",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Notification })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: NotificationCreateInput
  ): Promise<Notification> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        minutesBefore: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Notification",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Notification] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(NotificationFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Notification[]> {
    const args = plainToClass(NotificationFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        minutesBefore: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Notification",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Notification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: NotificationWhereUniqueInput
  ): Promise<Notification | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        minutesBefore: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Notification",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Notification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: NotificationWhereUniqueInput,
    @common.Body() data: NotificationUpdateInput
  ): Promise<Notification | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          minutesBefore: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Notification",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Notification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: NotificationWhereUniqueInput
  ): Promise<Notification | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          minutesBefore: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CompanySetNotification",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/companySetNotifications")
  @ApiNestedQuery(CompanySetNotificationFindManyArgs)
  async findManyCompanySetNotifications(
    @common.Req() request: Request,
    @common.Param() params: NotificationWhereUniqueInput
  ): Promise<CompanySetNotification[]> {
    const query = plainToClass(
      CompanySetNotificationFindManyArgs,
      request.query
    );
    const results = await this.service.findCompanySetNotifications(params.id, {
      ...query,
      select: {
        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        customText: true,
        id: true,

        notification: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Notification",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/companySetNotifications")
  async connectCompanySetNotifications(
    @common.Param() params: NotificationWhereUniqueInput,
    @common.Body() body: CompanySetNotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      companySetNotifications: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Notification",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/companySetNotifications")
  async updateCompanySetNotifications(
    @common.Param() params: NotificationWhereUniqueInput,
    @common.Body() body: CompanySetNotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      companySetNotifications: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Notification",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/companySetNotifications")
  async disconnectCompanySetNotifications(
    @common.Param() params: NotificationWhereUniqueInput,
    @common.Body() body: CompanySetNotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      companySetNotifications: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ReservationNotification",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/reservationNotifications")
  @ApiNestedQuery(ReservationNotificationFindManyArgs)
  async findManyReservationNotifications(
    @common.Req() request: Request,
    @common.Param() params: NotificationWhereUniqueInput
  ): Promise<ReservationNotification[]> {
    const query = plainToClass(
      ReservationNotificationFindManyArgs,
      request.query
    );
    const results = await this.service.findReservationNotifications(params.id, {
      ...query,
      select: {
        createdAt: true,
        customText: true,
        id: true,

        notification: {
          select: {
            id: true,
          },
        },

        reservation: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Notification",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/reservationNotifications")
  async connectReservationNotifications(
    @common.Param() params: NotificationWhereUniqueInput,
    @common.Body() body: ReservationNotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reservationNotifications: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Notification",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/reservationNotifications")
  async updateReservationNotifications(
    @common.Param() params: NotificationWhereUniqueInput,
    @common.Body() body: ReservationNotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reservationNotifications: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Notification",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/reservationNotifications")
  async disconnectReservationNotifications(
    @common.Param() params: NotificationWhereUniqueInput,
    @common.Body() body: ReservationNotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reservationNotifications: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
