/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CompanySetNotificationListRelationFilter } from "../../companySetNotification/base/CompanySetNotificationListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { IntFilter } from "../../util/IntFilter";
import { ReservationNotificationListRelationFilter } from "../../reservationNotification/base/ReservationNotificationListRelationFilter";
@InputType()
class NotificationWhereInput {
  @ApiProperty({
    required: false,
    type: () => CompanySetNotificationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CompanySetNotificationListRelationFilter)
  @IsOptional()
  @Field(() => CompanySetNotificationListRelationFilter, {
    nullable: true,
  })
  companySetNotifications?: CompanySetNotificationListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  minutesBefore?: IntFilter;

  @ApiProperty({
    required: false,
    type: () => ReservationNotificationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ReservationNotificationListRelationFilter)
  @IsOptional()
  @Field(() => ReservationNotificationListRelationFilter, {
    nullable: true,
  })
  reservationNotifications?: ReservationNotificationListRelationFilter;
}
export { NotificationWhereInput };
