/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateReservableSlotArgs } from "./CreateReservableSlotArgs";
import { UpdateReservableSlotArgs } from "./UpdateReservableSlotArgs";
import { DeleteReservableSlotArgs } from "./DeleteReservableSlotArgs";
import { ReservableSlotFindManyArgs } from "./ReservableSlotFindManyArgs";
import { ReservableSlotFindUniqueArgs } from "./ReservableSlotFindUniqueArgs";
import { ReservableSlot } from "./ReservableSlot";
import { ReservationFindManyArgs } from "../../reservation/base/ReservationFindManyArgs";
import { Reservation } from "../../reservation/base/Reservation";
import { TimeSlot } from "../../timeSlot/base/TimeSlot";
import { ReservableSlotService } from "../reservableSlot.service";

@graphql.Resolver(() => ReservableSlot)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ReservableSlotResolverBase {
  constructor(
    protected readonly service: ReservableSlotService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "read",
    possession: "any",
  })
  async _reservableSlotsMeta(
    @graphql.Args() args: ReservableSlotFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [ReservableSlot])
  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "read",
    possession: "any",
  })
  async reservableSlots(
    @graphql.Args() args: ReservableSlotFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ReservableSlot[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "ReservableSlot",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => ReservableSlot, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "read",
    possession: "own",
  })
  async reservableSlot(
    @graphql.Args() args: ReservableSlotFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ReservableSlot | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "ReservableSlot",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => ReservableSlot)
  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "create",
    possession: "any",
  })
  async createReservableSlot(
    @graphql.Args() args: CreateReservableSlotArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ReservableSlot> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "ReservableSlot",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ReservableSlot"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        timeSlot: {
          connect: args.data.timeSlot,
        },
      },
    });
  }

  @graphql.Mutation(() => ReservableSlot)
  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "update",
    possession: "any",
  })
  async updateReservableSlot(
    @graphql.Args() args: UpdateReservableSlotArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ReservableSlot | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "ReservableSlot",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ReservableSlot"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          timeSlot: {
            connect: args.data.timeSlot,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ReservableSlot)
  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "delete",
    possession: "any",
  })
  async deleteReservableSlot(
    @graphql.Args() args: DeleteReservableSlotArgs
  ): Promise<ReservableSlot | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Reservation])
  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "read",
    possession: "any",
  })
  async reservations(
    @graphql.Parent() parent: ReservableSlot,
    @graphql.Args() args: ReservationFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Reservation[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Reservation",
    });
    const results = await this.service.findReservations(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => TimeSlot, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "read",
    possession: "any",
  })
  async timeSlot(
    @graphql.Parent() parent: ReservableSlot,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<TimeSlot | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "TimeSlot",
    });
    const result = await this.service.getTimeSlot(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
