/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ReservableSlotService } from "../reservableSlot.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReservableSlotCreateInput } from "./ReservableSlotCreateInput";
import { ReservableSlotWhereInput } from "./ReservableSlotWhereInput";
import { ReservableSlotWhereUniqueInput } from "./ReservableSlotWhereUniqueInput";
import { ReservableSlotFindManyArgs } from "./ReservableSlotFindManyArgs";
import { ReservableSlotUpdateInput } from "./ReservableSlotUpdateInput";
import { ReservableSlot } from "./ReservableSlot";
import { ReservationFindManyArgs } from "../../reservation/base/ReservationFindManyArgs";
import { Reservation } from "../../reservation/base/Reservation";
import { ReservationWhereUniqueInput } from "../../reservation/base/ReservationWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReservableSlotControllerBase {
  constructor(
    protected readonly service: ReservableSlotService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ReservableSlot })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: ReservableSlotCreateInput
  ): Promise<ReservableSlot> {
    return await this.service.create({
      data: {
        ...data,

        timeSlot: {
          connect: data.timeSlot,
        },
      },
      select: {
        createdAt: true,
        dateTimeFrom: true,
        dateTimeTo: true,
        id: true,
        isActive: true,
        seatsLeft: true,

        timeSlot: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [ReservableSlot] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ReservableSlotFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<ReservableSlot[]> {
    const args = plainToClass(ReservableSlotFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        dateTimeFrom: true,
        dateTimeTo: true,
        id: true,
        isActive: true,
        seatsLeft: true,

        timeSlot: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ReservableSlot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ReservableSlotWhereUniqueInput
  ): Promise<ReservableSlot | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        dateTimeFrom: true,
        dateTimeTo: true,
        id: true,
        isActive: true,
        seatsLeft: true,

        timeSlot: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ReservableSlot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ReservableSlotWhereUniqueInput,
    @common.Body() data: ReservableSlotUpdateInput
  ): Promise<ReservableSlot | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          timeSlot: {
            connect: data.timeSlot,
          },
        },
        select: {
          createdAt: true,
          dateTimeFrom: true,
          dateTimeTo: true,
          id: true,
          isActive: true,
          seatsLeft: true,

          timeSlot: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ReservableSlot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ReservableSlotWhereUniqueInput
  ): Promise<ReservableSlot | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          dateTimeFrom: true,
          dateTimeTo: true,
          id: true,
          isActive: true,
          seatsLeft: true,

          timeSlot: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Reservation",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/reservations")
  @ApiNestedQuery(ReservationFindManyArgs)
  async findManyReservations(
    @common.Req() request: Request,
    @common.Param() params: ReservableSlotWhereUniqueInput
  ): Promise<Reservation[]> {
    const query = plainToClass(ReservationFindManyArgs, request.query);
    const results = await this.service.findReservations(params.id, {
      ...query,
      select: {
        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        isAccepted: true,

        reservableSlot: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/reservations")
  async connectReservations(
    @common.Param() params: ReservableSlotWhereUniqueInput,
    @common.Body() body: ReservationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reservations: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/reservations")
  async updateReservations(
    @common.Param() params: ReservableSlotWhereUniqueInput,
    @common.Body() body: ReservationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reservations: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "ReservableSlot",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/reservations")
  async disconnectReservations(
    @common.Param() params: ReservableSlotWhereUniqueInput,
    @common.Body() body: ReservationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reservations: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
