/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateCompanySetNotificationArgs } from "./CreateCompanySetNotificationArgs";
import { UpdateCompanySetNotificationArgs } from "./UpdateCompanySetNotificationArgs";
import { DeleteCompanySetNotificationArgs } from "./DeleteCompanySetNotificationArgs";
import { CompanySetNotificationFindManyArgs } from "./CompanySetNotificationFindManyArgs";
import { CompanySetNotificationFindUniqueArgs } from "./CompanySetNotificationFindUniqueArgs";
import { CompanySetNotification } from "./CompanySetNotification";
import { Company } from "../../company/base/Company";
import { Notification } from "../../notification/base/Notification";
import { CompanySetNotificationService } from "../companySetNotification.service";

@graphql.Resolver(() => CompanySetNotification)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CompanySetNotificationResolverBase {
  constructor(
    protected readonly service: CompanySetNotificationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CompanySetNotification",
    action: "read",
    possession: "any",
  })
  async _companySetNotificationsMeta(
    @graphql.Args() args: CompanySetNotificationFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [CompanySetNotification])
  @nestAccessControl.UseRoles({
    resource: "CompanySetNotification",
    action: "read",
    possession: "any",
  })
  async companySetNotifications(
    @graphql.Args() args: CompanySetNotificationFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CompanySetNotification[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "CompanySetNotification",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => CompanySetNotification, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CompanySetNotification",
    action: "read",
    possession: "own",
  })
  async companySetNotification(
    @graphql.Args() args: CompanySetNotificationFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CompanySetNotification | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "CompanySetNotification",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => CompanySetNotification)
  @nestAccessControl.UseRoles({
    resource: "CompanySetNotification",
    action: "create",
    possession: "any",
  })
  async createCompanySetNotification(
    @graphql.Args() args: CreateCompanySetNotificationArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CompanySetNotification> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "CompanySetNotification",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"CompanySetNotification"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        company: {
          connect: args.data.company,
        },

        notification: {
          connect: args.data.notification,
        },
      },
    });
  }

  @graphql.Mutation(() => CompanySetNotification)
  @nestAccessControl.UseRoles({
    resource: "CompanySetNotification",
    action: "update",
    possession: "any",
  })
  async updateCompanySetNotification(
    @graphql.Args() args: UpdateCompanySetNotificationArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CompanySetNotification | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "CompanySetNotification",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"CompanySetNotification"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          company: {
            connect: args.data.company,
          },

          notification: {
            connect: args.data.notification,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CompanySetNotification)
  @nestAccessControl.UseRoles({
    resource: "CompanySetNotification",
    action: "delete",
    possession: "any",
  })
  async deleteCompanySetNotification(
    @graphql.Args() args: DeleteCompanySetNotificationArgs
  ): Promise<CompanySetNotification | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Company, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CompanySetNotification",
    action: "read",
    possession: "any",
  })
  async company(
    @graphql.Parent() parent: CompanySetNotification,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Company | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Company",
    });
    const result = await this.service.getCompany(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => Notification, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CompanySetNotification",
    action: "read",
    possession: "any",
  })
  async notification(
    @graphql.Parent() parent: CompanySetNotification,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Notification | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Notification",
    });
    const result = await this.service.getNotification(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
